## Assignment : 06 - Linear Regression

### 1. Loading and preprocssing the data

In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_california_housing

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [2]:
housing = fetch_california_housing()

df=pd.DataFrame(housing.data, columns=housing.feature_names)
df['PRICE'] = housing.target

df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,PRICE
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [3]:
print(df.shape)
df.info()
df.describe()

(20640, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   PRICE       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,PRICE
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [24]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
PRICE         0
dtype: int64

In [25]:
X = df.drop('PRICE', axis=1)
y = df['PRICE']

#### Preprocessing Explanation

1. Converted the dataset into a pandas DataFrame for easier handling and analysis.
2. Checked for missing values using 'isnull().sum()
3. No missing values were found in the dataset.
4. Applied feature scaling using StandardScaler because algorithms like SVR and Linear Regression perform better when features are on a similar scale.

#### Split data and Scaling

In [6]:
X_train, X_test, y_train, y_test, = train_test_split(
    X, y,
    test_size = 0.2,
    random_state = 42

)
print(X_train.shape)
print(X_test.shape)

(16512, 8)
(4128, 8)

In [26]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### 2. Regression Algorithms Implementation

#### 1. Linear Regression

* Linear Regression predicts the target value by finding the best linear relationship between input features an doutput.
* It is suitable for this dataset because housing prices often have linear relationships with features such as income, rooms, and population.

In [8]:
lr = LinearRegression()

lr.fit(X_train_scaled, y_train)
y_pred_lr = lr.predict(X_test_scaled)

mse_lr = mean_squared_error(y_test, y_pred_lr)
mae_lr = mean_absolute_error(y_test, y_pred_lr)

r2_lr = r2_score(y_test,y_pred_lr)

print("Linear Regression Results")
print("MSE:", mse_lr)
print("MAE:", mae_lr)
print("R2 SCORE:", r2_lr)

Linear Regression Results
MSE: 0.5558915986952442
MAE: 0.5332001304956566
R2 SCORE: 0.575787706032451

#### 2. Decision Tree Regressor

* Decision Tree Regressor slits the data into branches based on feature values to make predicions.
* It is suitable because it can capture non-linear relationships in housing data.

In [9]:
dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

mse_dt = mean_squared_error(y_test, y_pred_dt)
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Results")
print("MSE:", mse_dt)
print("MAE:", mae_dt)
print("R2 SCORE:", r2_dt)

Decision Tree Results
MSE: 0.506845371908188
MAE: 0.4576055474806202
R2 SCORE: 0.6132158888375596

#### 3. Random Forest Regressor

* Random Forest combines multiple decision trees averages their predictions.
* It improves accuracy and reduces overfitting, making it highly effective for housing price prediction.

In [10]:
rf = RandomForestRegressor(random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

mse_rf = mean_squared_error(y_test, y_pred_rf)
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Results:")
print("MSE:", mse_rf)
print("MAE:", mae_rf)
print("R2 SCORE:", r2_rf)

Random Forest Results:
MSE: 0.25602128637529376
MAE: 0.3275064112160854
R2 SCORE: 0.8046248990761814

#### 4. Gradient Boosting Regressor

* Gradient Boosting builds trees sequentially, where each tree corrects errors from the previous one.
* It is suitable because it handles complex patterns and usually provides high prediction accuracy.

In [13]:
gb = GradientBoostingRegressor(random_state=42)

gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

mse_gb = mean_squared_error(y_test, y_pred_gb)
mae_gb = mean_absolute_error(y_test, y_pred_gb)
r2_gb = r2_score(y_test, y_pred_gb)

print("Gradient Boosting Results:")
print("MSE:", mse_gb)
print("MAE:", mae_gb)
print("R2 SCORE:", r2_gb)

Gradient Boosting Results:
MSE: 0.2939973248643864
MAE: 0.3716425690425596
R2 SCORE: 0.7756446042829697

#### 5. Support Vector Regressor (SVR)

* SVR tries to fit the best boundary within a margin of tolerance.
* It works well for complex datasets and benefits from feature scaling.

In [14]:
svr = SVR()
svr.fit(X_train, y_train)

y_pred_svr = svr.predict(X_test)

mse_svr = mean_squared_error(y_test, y_pred_svr)
mae_svr = mean_absolute_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print("SVR Results:")
print("MSE:", mse_svr)
print("MAE:", mae_svr)
print("R2 SCORE:", r2_svr)

SVR Results:
MSE: 1.3320115421348793
MAE: 0.8599506583445774
R2 SCORE: -0.016485360107177494

In [20]:
results = pd.DataFrame({
    'Model': [
        'Linear Regression',
        'Decision Tree',
        'Random Forest',
        'Gradient Boosting',
        'SVR'
    ],

    'MSE': [
        mse_lr,
        mse_dt,
        mse_rf,
        mse_gb,
        mse_svr
    ],
    'MAE': [
        mae_lr,
        mae_dt,
        mae_rf,
        mae_gb,
        mae_svr

    ],
    'R2 SCORE': [
        r2_lr,
        r2_dt,
        r2_rf,
        r2_gb,
        r2_svr
    ]

})

results

               Model       MSE       MAE  R2 SCORE
0  Linear Regression  0.555892  0.533200  0.575788
1      Decision Tree  0.506845  0.457606  0.613216
2      Random Forest  0.256021  0.327506  0.804625
3  Gradient Boosting  0.293997  0.371643  0.775645
4                SVR  1.332012  0.859951 -0.016485

### 3. Model Evaluation and Conclusion.

* Among all the 5 models, Random Forest Regressor and Gradient Boosting Regressor perofrmed the best. Because they acheived lower MSE and MAE values and higher R2 (R-Square) values.
* The worst-performing model was Linear Regressor because it assumes a simple linear relationship, which may not fully represent housing price pattern.
* These ensemble models work well for complex datasets because they capture non-linear relationsips effectively.

-------------------------------------------------------------------------------------------------------------------------------------------------------